# Generated by Django 3.0.8 on 2020-07-15 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deviation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.TextField()),
                ('object_id', models.TextField()),
                ('product_id', models.TextField()),
                ('shift_number', models.TextField()),
                ('shiftbegt', models.DateTimeField()),
                ('shiftendt', models.DateTimeField()),
                ('shipment', models.IntegerField()),
                ('reception', models.IntegerField()),
                ('deviation', models.IntegerField()),
                ('version', models.IntegerField()),
            ],
        ),
    ]
